package ecommerce

const (
	ResponseGroupAccessories = "Accessories"
	ResponseGroupAlternateVersion = "AlternateVersion"
	ResponseGroupBrowseNodeInfo = "BrowseNodeInfo"
	ResponseGroupBrowseNodes = "BrowseNodes"
	ResponseGroupCart = "Cart"
	ResponseGroupCartNewReleases = "CartNewReleases"
	ResponseGroupCartTopSellers = "CartTopSellers"
	ResponseGroupCartSimilarities = "CartSimilarities"
	ResponseGroupEditorialReview = "EditorialReview"
	ResponseGroupImages = "Images"
	ResponseGroupItemAttributes = "ItemAttributes"
	ResponseGroupItemIds = "ItemIds"
	ResponseGroupLarge = "Large"
	ResponseGroupMedium = "Medium"
	ResponseGroupMostGifted = "MostGifted"
	ResponseGroupMostWishedFor = "MostWishedFor"
	ResponseGroupNewReleases = "NewReleases"
	ResponseGroupOfferFull = "OfferFull"
	ResponseGroupOfferListings = "OfferListings"
	ResponseGroupOffers = "Offers"
	ResponseGroupOfferSummary = "OfferSummary"
	ResponseGroupPromotionSummary = "PromotionSummary"
	ResponseGroupRelatedItems = "RelatedItems"
	ResponseGroupRequest = "Request"
	ResponseGroupReviews = "Reviews"
	ResponseGroupSalesRank = "SalesRank"
	ResponseGroupSearchBins = "SearchBins"
	ResponseGroupSimilarities = "Similarities"
	ResponseGroupSmall = "Small"
	ResponseGroupTopSellers = "TopSellers"
	ResponseGroupTracks = "Tracks"
	ResponseGroupVariations = "Variations"
	ResponseGroupVariationImages = "VariationImages"
	ResponseGroupVariationMatrix = "VariationMatrix"
	ResponseGroupVariationOffers = "VariationOffers"
	ResponseGroupVariationSummary = "VariationSummary"
)
